[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x', 'openssl']

[phases.install]
cmds = ['cd api && npm ci']

[phases.build]
cmds = ['cd api && npm run build', 'cd api && npx prisma generate']

[start]
cmd = 'cd api && npx prisma db push --accept-data-loss && node dist/index.js'
