[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x', 'openssl']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build', 'npx prisma generate']

[start]
cmd = 'npx prisma db push --accept-data-loss && node dist/index.js'
